# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 552)
        MainWindow.setStyleSheet("QPushButton{\n"
"    color: rgb(170, 170, 255);\n"
"    background-color: rgb(85, 255, 255);\n"
"    background-color: rgb(255, 170, 127);\n"
"    background-color: rgb(255, 170, 0);\n"
"    height:50px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 20, 471, 241))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.voitureBtn = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.voitureBtn.setFont(font)
        self.voitureBtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.voitureBtn.setObjectName("voitureBtn")
        self.horizontalLayout_2.addWidget(self.voitureBtn)
        self.clientbtn = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.clientbtn.setFont(font)
        self.clientbtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.clientbtn.setObjectName("clientbtn")
        self.horizontalLayout_2.addWidget(self.clientbtn)
        self.horizontalLayout.addWidget(self.widget_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 20, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 170, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-110, 180, 731, 451))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("car-rent-logo-design-template-symbol-icon-car-rental-rental-car-logo-car-vector-illustration-157196594.jpg"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.voitureBtn.setText(_translate("MainWindow", "gerer voiture"))
        self.clientbtn.setText(_translate("MainWindow", "gerer client"))
        self.label.setText(_translate("MainWindow", "Location de Voiture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
