# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 594)
        MainWindow.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#centralwidget{\n"
"background-color:rgb(255, 170, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-40, 0, 651, 591))
        self.widget.setTabletTracking(True)
        self.widget.setStatusTip("")
        self.widget.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 255, 127);\n"
"background-color: rgb(170, 170, 255);\n"
"background-color: rgb(181, 181, 136);\n"
"background-color: rgb(191, 191, 191);\n"
"background-color: rgb(255, 255, 255);\n"
"QPushButton\n"
"{\n"
"background:red;\n"
"border-radus:15px;\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 30, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 260, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(50, 370, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(50, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_6.setObjectName("label_6")
        self.first_namefield = QtWidgets.QLineEdit(self.widget)
        self.first_namefield.setGeometry(QtCore.QRect(170, 250, 201, 31))
        self.first_namefield.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:orange;\n"
"border-bottom:1px solid orange;\n"
"")
        self.first_namefield.setInputMethodHints(QtCore.Qt.ImhNone)
        self.first_namefield.setInputMask("")
        self.first_namefield.setObjectName("first_namefield")
        self.last_namefield = QtWidgets.QLineEdit(self.widget)
        self.last_namefield.setGeometry(QtCore.QRect(172, 310, 201, 31))
        self.last_namefield.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:orange;\n"
"border-bottom:1px solid orange;\n"
"")
        self.last_namefield.setObjectName("last_namefield")
        self.usernamefield = QtWidgets.QLineEdit(self.widget)
        self.usernamefield.setGeometry(QtCore.QRect(180, 360, 201, 21))
        self.usernamefield.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:orange;\n"
"border-bottom:1px solid orange;\n"
"")
        self.usernamefield.setObjectName("usernamefield")
        self.passwordfield = QtWidgets.QLineEdit(self.widget)
        self.passwordfield.setGeometry(QtCore.QRect(180, 400, 201, 31))
        self.passwordfield.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:orange;\n"
"border-bottom:1px solid orange;\n"
"")
        self.passwordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordfield.setObjectName("passwordfield")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(30, 20, 621, 111))
        self.label_7.setStyleSheet("image: url(:/newPrefix/images.png);\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 170, 0);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(280, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.btn_signup = QtWidgets.QPushButton(self.widget)
        self.btn_signup.setGeometry(QtCore.QRect(170, 520, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.btn_signup.setFont(font)
        self.btn_signup.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radus:15px;")
        self.btn_signup.setObjectName("btn_signup")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(420, 270, 231, 191))
        self.widget_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 221, 171))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/download.png"))
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(50, 470, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_9.setObjectName("label_9")
        self.C_passwordfield = QtWidgets.QLineEdit(self.widget)
        self.C_passwordfield.setGeometry(QtCore.QRect(200, 460, 201, 31))
        self.C_passwordfield.setStyleSheet("background:transparent;\n"
"border:none;\n"
"color:orange;\n"
"border-bottom:1px solid orange;\n"
"")
        self.C_passwordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.C_passwordfield.setObjectName("C_passwordfield")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setGeometry(QtCore.QRect(60, 150, 75, 31))
        self.pushButton_9.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-flèche-gauche-52.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(48, 36))
        self.pushButton_9.setObjectName("pushButton_9")
        self.error2 = QtWidgets.QLabel(self.widget)
        self.error2.setGeometry(QtCore.QRect(170, 290, 181, 16))
        self.error2.setText("")
        self.error2.setObjectName("error2")
        self.error3 = QtWidgets.QLabel(self.widget)
        self.error3.setGeometry(QtCore.QRect(170, 350, 201, 16))
        self.error3.setText("")
        self.error3.setObjectName("error3")
        self.error5 = QtWidgets.QLabel(self.widget)
        self.error5.setGeometry(QtCore.QRect(190, 440, 181, 16))
        self.error5.setText("")
        self.error5.setObjectName("error5")
        self.error1 = QtWidgets.QLabel(self.widget)
        self.error1.setGeometry(QtCore.QRect(180, 390, 181, 16))
        self.error1.setText("")
        self.error1.setObjectName("error1")
        self.error6 = QtWidgets.QLabel(self.widget)
        self.error6.setGeometry(QtCore.QRect(200, 500, 181, 16))
        self.error6.setText("")
        self.error6.setObjectName("error6")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(180, 570, 181, 16))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(190, 570, 181, 16))
        self.error.setText("")
        self.error.setObjectName("error")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sign Up"))
        self.label_2.setText(_translate("MainWindow", "first Name"))
        self.label_3.setText(_translate("MainWindow", "last Name"))
        self.label_5.setText(_translate("MainWindow", "Login"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.label_8.setText(_translate("MainWindow", "Sign Up"))
        self.btn_signup.setText(_translate("MainWindow", "Create account"))
        self.label_9.setText(_translate("MainWindow", "Confirm Password"))
import rsc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
